services:
  postgres:
    image: postgres:15-alpine
    container_name: supoclip-postgres-simple
    environment:
      POSTGRES_DB: supoclip
      POSTGRES_USER: supoclip
      POSTGRES_PASSWORD: supoclip_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.optimized
    container_name: supoclip-backend-simple
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://supoclip:supoclip_password@postgres:5432/supoclip
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  uploads:
    driver: local
  postgres_data:
    driver: local