services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    container_name: supoclip-frontend-simple
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    container_name: supoclip-backend-simple
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://supoclip:supoclip_password@postgres:5432/supoclip
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: supoclip-postgres-simple
    environment:
      POSTGRES_DB: supoclip
      POSTGRES_USER: supoclip
      POSTGRES_PASSWORD: supoclip_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
