services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: supoclip-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - BETTER_AUTH_SECRET=supoclip-dev-secret-key-2024-very-secure-and-unique-key-for-development-only
      - BETTER_AUTH_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: supoclip-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - uploads:/app/uploads
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+asyncpg://supoclip:supoclip_password@postgres:5432/supoclip
    restart: unless-stopped
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: supoclip-postgres-dev
    environment:
      POSTGRES_DB: supoclip
      POSTGRES_USER: supoclip
      POSTGRES_PASSWORD: supoclip_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  uploads:
    driver: local
  postgres_data:
    driver: local

networks:
  default:
    name: supoclip-dev-network
